// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rumpvpcviaijmxxnrujc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1bXB2cGN2aWFpam14eG5ydWpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MDk2NDYsImV4cCI6MjA2ODI4NTY0Nn0.TUFZW36oj4LqBD5fkC9gWtWu_E3bfrAjJ0CfhyaBFrQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});